"""Initial setup or Describe changes

Revision ID: 7ad51cdb1fb8
Revises: bb0b926742f5
Create Date: 2024-10-26 12:22:02.723166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad51cdb1fb8'
down_revision: Union[str, None] = 'bb0b926742f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
